### ISSUE TITLE
Pre-commit hooks should ignore all junk files

### ISSUE THREAD

**Issue by fredrik-bakke** [UniMath/SymmetryBookFormalization#664]
Some of the pre-commit hooks, like `generate_main_index_file.py`, don't properly behave when the `src` folder is dirty. For instance when a MAlonzo folder is present. To fix this, we can filter out patterns from the `.gitignore` file.

**Comment by fredrik-bakke** [comment]
I asked GPT4 for a solution:

> The easiest way to achieve this is by using the `pathspec` Python library, which allows you to match paths using `.gitignore` style patterns. 
> 
> First, you'll need to install the library. You can do this using pip:
> 
> ```bash
> pip install pathspec
> ```
> 
> Then, you can use the library in your script. You will need to read the contents of your `.gitignore` file and use them to compile a `PathSpec` object. Then you can use the `match_file` method on this object to test whether a given path should be ignored.
> 
> Here's how you can modify your `generate_index` function to ignore directories specified in your `.gitignore`:
> 
> ```python
> from pathspec import PathSpec
> from pathspec.patterns import GitWildMatchPattern
> 
> def generate_index(root, header):
>     status = 0
>     entry_lists = []
> 
>     # Read .gitignore file
>     with open('.gitignore', 'r') as f:
>         gitignore = f.read().splitlines()
> 
>     # Compile .gitignore file into a PathSpec
>     pathspec = PathSpec.from_lines(GitWildMatchPattern, gitignore)
> 
>     for namespace in sorted(utils.get_subdirectories_recursive(root)):
>         if namespace == 'temp':
>             continue
> 
>         # Test if path matches .gitignore
>         if pathspec.match_file(namespace):
>             continue
> 
>         entry_list, s = generate_namespace_entry_list(namespace)
>         entry_lists.append(entry_list)
>         status |= s
> 
>     index = f'{header}\n\n' + '\n\n'.join(entry_lists) + '\n'
>     return index, status
> ```
> 
> In this script, `pathspec.match_file(namespace)` returns `True` if the `namespace` matches any pattern in your `.gitignore`. If it does, then `continue` skips to the next iteration of the loop, effectively ignoring that directory.
> 
> Remember to take care of the relative paths. If your `.gitignore` file is not in the same directory as the script, you'll need to adjust the path when opening the file. Similarly, you'll need to make sure the paths you're testing with `match_file` are relative to the location of your `.gitignore`.

**Comment by VojtechStep** [comment]
Alternatively, we can ask Git itself to give us the list of files it sees, that's what pre-commit does internally - see [here](https://github.com/pre-commit/pre-commit/blob/main/pre_commit/git.py#L155).
